# Generated by Django 5.0.4 on 2024-04-24 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.SmallIntegerField(choices=[(1, 'AUDI'), (2, 'BMW'), (3, 'CHEVROLET - GM'), (4, 'FERRARI'), (5, 'FIAT'), (6, 'FORD'), (7, 'HONDA'), (8, 'HYUNDAI'), (9, 'VOLKSWAGEN')])),
                ('modelo', models.CharField(max_length=100)),
                ('cor', models.SmallIntegerField(choices=[(1, 'BRANCO'), (2, 'PRETO'), (3, 'AMARELO'), (4, 'AZUL'), (5, 'VERMELHO'), (6, 'PRATA'), (7, 'VERDE'), (8, 'CINZA')])),
                ('combustivel', models.SmallIntegerField(choices=[(1, 'GASOLINA'), (2, 'DIESEL'), (3, 'FLEX'), (4, 'ETANOL')])),
            ],
        ),
    ]
