# Generated by Django 5.0.4 on 2024-04-24 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='ano',
            field=models.IntegerField(default=2003),
            preserve_default=False,
        ),
    ]
